### ISSUE TITLE
Various mercenaries and pirates have a partially pink and white helmet

### ISSUE THREAD

**Issue by henbagle** [henbagle/LE1CommunityPatch#15]
**Describe the bug**
ERCS Guard on Noveria (in the synthetic insights lab fight) has a partially pink and white helmet, bug also reported on various mercenaries and pirates

**Screenshots & Saves**
![TMjP5Q6 - Tydeous](https://user-images.githubusercontent.com/8151477/126053525-fabf0679-2b62-4ed6-bc7f-8379cd931051.jpg)
![RiygHEs - Tydeous](https://user-images.githubusercontent.com/8151477/126053526-14e92a6e-64db-4208-8ba6-6d84fe806bfa.jpg)

**Comment by henbagle** [comment]
Other instances: Cerberus Snipers on Nepheron, Alliance Soldier from UNC: Listening Post Alpha on Nepmos

**Comment by henbagle** [comment]
The mesh in question is HMM_BTR_HVY_MDL, may be misspelled as HMM_BRT_HVY_MDL in some contexts. The visors have a tint map, and inappropriate colors appear to be applied to it. The issue is in the MaterialInstanceConstant in each file that uses this mesh. Changing the HGR_Colour_01 (white part of visor) and HGR_Colour_02 (Pink/red part of visor) in the VectorParameterValues array to more appropriate colors fixes the issue.

For example, Export 9802 in file BIOA_ICE20_06_DSG.pcc is the affected export for the two mercenaries in the Synthetic Insights office (can be fought after getting the data from Lorik Qui'in's computer)

Finding all usages of this visor and fixing the tints will be the fix for this bug.

**Comment by henbagle** [comment]
Non-exhaustive list of files where this is an issue:
BIOA_ICE20_06_DSG.pcc
BIOA_PRO10_02_DSG.pcc
BIOA_UNC10_01_DSG.pcc
BIOA_UNC10_02_DSG.pcc
BIOA_UNC11_01_DSG.pcc
BIOA_UNC11_02_DSG.pcc
BIOA_UNC13_02_DSG.pcc
BIOA_UNC20_00_DSG.pcc
BIOA_UNC30_00_DSG.pcc
BIOA_UNC31_02_DSG.pcc
BIOA_UNC42_00_DSG.pcc
BIOA_UNC42_02_DSG.pcc
BIOA_UNC52_00_DSG.pcc
BIOA_UNC52_00survey_DSG.pcc
BIOA_UNC52_00torch_DSG.pcc
BIOA_UNC53_00_DSG.pcc
BIOA_UNC54_00_DSG.pcc
BIOA_UNC61_02_DSG.pcc
BIOA_UNC62_01_DSG.pcc
BIOA_UNC62_02_DSG.pcc
BIOA_UNC73_01_DSG.pcc
BIOA_UNC80_02_DSG.pcc
BIOA_UNC82_01_DSG.pcc
BIOA_UNC82_02_DSG.pcc
BIOA_UNC90_01_DSG.pcc
BIOA_UNC90_02_DSG.pcc
BIOA_UNC92_01_DSG.pcc
BIOA_UNC92_02_DSG.pcc

**Comment by henbagle** [comment]
Fixed via the method listed above, changing the HGR_Colour_01 and 02 of each MaterialInstanceConstant in the affected files. The HGR_Colour_01 was changed to match the armor color of the wearer. Where necessary, the MaterialInstanceConstant was cloned so two different colors could be used, and the Materials property was added to the usage of the visor to specify an instance.

**Comment by henbagle** [comment]
Hex colors for HGR_Colour_01 of each armor
grey/corp sec: #FF212329
green/cerberus: #FF060A05
cream/mercenary 02: #FF998755
black/mercenary 01: #FF0A0D0F
jungle camo: #FF0A0A05
mercenary 02 MED black: #00121517

**Comment by henbagle** [comment]
Bugfix has now been properly applied in BIOA_UNC11_02_DSG.pcc

**Comment by mkhaar** [comment]
This issue still exists in the outside map for Bring Down the Sky. The batarians in the minefield all have pink visors with the current version of the patch.

The file in question is `BIOA_UNC52_00torch_DSG`. This file is listed above in a comment, but is definitely not present in the current version of the patch.
